
spring:
  datasource:
    url: jdbc:mysql://10.11.2.51:3306/inm-market-center-dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: WY3aIYNc02Xxh0Zx
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 10000
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.macro.mall: debug