spring:
  datasource:
    url: jdbc:mysql://10.11.2.51:3306/inm-market-center-dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: WY3aIYNc02Xxh0Zx
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: elasticsearch
  elasticsearch:
    rest:
      uris: http://localhost:9200
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.macro.mall: debug